a = input('Digite algo: ')
print ('O tipo primitivo é -->', type(a))
print('Só Tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico?', a.isalnum())
